### PR TITLE
EndianBitConverter refactor for better performance

### PR DESCRIPTION
**Pull request by JBildstein**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/JimBobSquarePants/ImageSharp/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practise as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description

Big/Little EndianBitConverter now uses fixed size bit shifting methods (16,32,64bit) instead of a loop. In some cases it also uses unsafe code tricks to convert floating point to integer values and vice versa (compared to using a struct with LayoutKind.Explicit).
The EndianBitConverter.cs file has been split up into multiple files to remove the regions and keep readability.
A few more tests have been added to the already existing ones. There are still tests missing for the float/double/decimal types. Not sure how to best handle that.

Speed tests (Stopwatch, warmup loop and 5 full repeats) show a speedup of roughly 40% to 50% depending on the method. The Copy/GetBytes methods have less speedup than the To<Type> methods.

### CODE REVIEW

**Comment by dlemstra** [comment]
Do you have some before/after benchmarks?

**Comment by JBildstein** [comment]
Sure, here's the used code (run in Release mode, no debugger attached):

```
int inputInt = 4512445;
long inputLong = inputInt;
byte[] buffer = new byte[16];
byte[] data = { 0x1D, 0x5F, 0xA2, 0x7E, 0x1D, 0x5F, 0xA2, 0x7E, 0x1D, 0x5F, 0xA2, 0x7E, 0x1D, 0x5F, 0xA2, 0x7E };

Stopwatch watch = new Stopwatch();
EndianBitConverter converter = EndianBitConverter.GetConverter(Endianness.BigEndian);

for (int i = 0; i < 5; i++)
{
    for (int j = 0; j < 100; j++)
    {
        int resultInt = converter.ToInt32(data, 0);
        // long resultLong = converter.ToInt64(data, 0);
        // converter.CopyBytes(inputInt, buffer, 0);
        // converter.CopyBytes(inputLong, buffer, 0);
    }
    watch.Restart();
    for (int j = 0; j < 200000000; j++)
    {
        int resultInt = converter.ToInt32(data, 0);
        // long resultLong = converter.ToInt64(data, 0);
        // converter.CopyBytes(inputInt, buffer, 0);
        // converter.CopyBytes(inputLong, buffer, 0);
    }
    watch.Stop();
    Console.WriteLine(watch.ElapsedMilliseconds);
}
```
Results new version:

 | Run | ToInt32 | ToInt64 | CopyBytes (int) | CopyBytes (long) |
 | --- | --- | --- | --- | --- |
 | 1 | 495 | 752 | 652 | 1011 | 
 | 2 | 480 | 714 | 621 | 998 | 
 | 3 | 475 | 713 | 618 | 993 | 
 | 4 | 475 | 698 | 620 | 987 | 
 | 5 | 475 | 698 | 629 | 1000 | 

Results old version:

 | Run | ToInt32 | ToInt64 | CopyBytes (int) | CopyBytes (long) |
 | --- | --- | --- | --- | --- |
 | 1 | 1007 | 1509 | 1088 | 1653 | 
 | 2 | 1000 | 1470 | 1054 | 1644 | 
 | 3 | 998 | 1459 | 1051 | 1616 | 
 | 4 | 1002 | 1456 | 1050 | 1630 | 
 | 5 | 1020 | 1469 | 1063 | 1659 |

**Comment by tocsoft** [comment]
I've had a look over this, do we need the `GetBytes(...)` methods in the bit converter? I feel we don't want to make it easier to accidentally use code path that can cause high allocations.

**Comment by JimBobSquarePants** [comment]
@tocsoft I get your point but I'd rather keep them in for now just to make the class BitConverter API complete. 

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/BitConverter.cs

**Comment by JimBobSquarePants** [comment]
2X speedup plus much cleaner code. I'm happy to merge this unless someone spots something I've missed?

**Pull request merged**
