### PR TITLE
[WIP] Docfx based documentation

### LINKED ISSUE #6: API docs
_From @JimBobSquarePants on January 13, 2016 0:43_

I would like to create documentation like the following: 

http://dotnet.github.io/

MS are using the library below but I can't seem to follow the instructions.

http://dotnet.github.io/docfx/

_Copied from original issue: JimBobSquarePants/ImageProcessor#297_

### PR DESCRIPTION
**Pull request by M-Zuber**
Closes #6 

## TODO's

- [ ] Fix the text in the `index.md` files
- [ ] Theme?

Anything else?

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
Great to see this open.

How easy is it to set a custom theme? 

Also, how easy would it be to preserve a CNAME file in the output? Does the builder clear everything out?

**Comment by M-Zuber** [comment]
Acknowledging your questions, but I do not know the answers to them yet. At a conference 14th & 15th, but if my remote connection works I will try and work on it

**Comment by JimBobSquarePants** [comment]
@M-Zuber Don't worry, no rush! 😄

**Comment by M-Zuber** [comment]
CNAME files are preserved.
As far as custom themes, as I assume most of what you want to do is css, I've prepared a file for what you need.
More can be done, but it should give you a starting point.

At this point, it just needs to be built and have a server started in `~/docs/`

**Comment by M-Zuber** [comment]
I would not merge this before a commit of cleaning up the docs folder as I think it should be starting blank and only filled by the CI, but what do you say?

**Comment by JimBobSquarePants** [comment]
Yeah, I agree. Only custom markdown should be present already. (I still need to read up on how that works)

**Comment by M-Zuber** [comment]
I'm going to close this out, in order to make a cleaner new PR

**Comment by JimBobSquarePants** [comment]
Yeah? OK, you're the boss! 😄

**Pull request closed without merging**
