### PR TITLE
Ensure Color structure stores elements in RGBA order

### PR DESCRIPTION
**Pull request by mellinoe**
@JimBobSquarePants I figured I'd take a shot at fixing this per our discussion yesterday. Let me know what you think about this approach. I added an additional test that ensures the bytes are laid out as expected in memory.

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
Ah excellent! 👍   @mellinoe  This is a good start, I wasn't looking forward to doing this.

There's a couple of other files that will require updating also to finish up.

All the protected methods here
https://github.com/JimBobSquarePants/ImageSharp/blob/d4f8f8ceac73d35617108701981789da534954e7/src/ImageSharp/Image/PixelAccessor.cs#L232

And their overrides here
https://github.com/JimBobSquarePants/ImageSharp/blob/d4f8f8ceac73d35617108701981789da534954e7/src/ImageSharp/PixelAccessor.cs

Looking at the original implementations, I don't believe we need to check for endianness since we know the order in which the bytes are stored and will deliver them the correct way in the decoders/encoders.

**Comment by dlemstra** [comment]
I think you are right that we can remove the endianness check since we don't care about the actual integer value. Feel free to remove them.

**Comment by mellinoe** [comment]
Could you give me a bit more guidance as to what the `PixelAccessor` does and what needs to be changed in it? Right now it looks fairly correct to me, but I'm not sure what the intended semantics are.

**Comment by mellinoe** [comment]
Since the current tests pass, maybe you could just show me a failing test case that I could add and then fix.

**Comment by JimBobSquarePants** [comment]
@mellinoe Yeah of course, The methods identified in `PixelAccessor<TColor, TPacked>` and the optimised `PixelAccessor` classes allow it to read and write to the encoders in the the requested order. These methods will eventually be used to optimise the codecs (Bmp has already been done)

`ComponentOrder.XYZW` is the equivalent of `RGBA` in `Color` and `ComponentOrder.ZYXW` of `BGRA`.

There is a visual test [DecodeThenEncodeImageFromStreamShouldSucceed](https://github.com/JimBobSquarePants/ImageSharp/blob/d4f8f8ceac73d35617108701981789da534954e7/tests/ImageSharp.Tests/Formats/GeneralFormatTests.cs#L48) Which should be giving your garbled output with your PR in its current status. Fixing, the order we read/write in the identified methods should fix them.

Hope that helps!

**Comment by mellinoe** [comment]
The test images look okay to me, as far as I can tell... Could you take a look for me and see if anything is wrong?

**Comment by JimBobSquarePants** [comment]
Yeah, will do. 🙂

**Comment by JimBobSquarePants** [comment]
Odd... I would have sworn we would have had to change those methods. 

@mellinoe  As long as everything is now working for you (no more red) then I'm happy to merge this. @dlemstra Can you just double check I've not missed something?

**Comment by dlemstra** [comment]
I just pushed some unit tests (https://github.com/JimBobSquarePants/ImageSharp/commit/e82a5f6e3c0e019d542e0471222d39a7f7a13fac) that make sure the optimized version of PixelAccessor still works after your changes. Copying in your file breaks these tests but its pretty easy to resolve. You will need to fix the order here: https://github.com/JimBobSquarePants/ImageSharp/blob/master/src/ImageSharp/PixelAccessor.cs#L63 and here https://github.com/JimBobSquarePants/ImageSharp/blob/master/src/ImageSharp/PixelAccessor.cs#L80.

**Comment by mellinoe** [comment]
Latest version should be correct, and tests work for me.

**Comment by dlemstra** [comment]
Looks great, and thanks for the help. I'll let you handle the merge @JimBobSquarePants.

**Comment by JimBobSquarePants** [comment]
Me also, Excellent stuff. Very much appreciated @mellinoe

**Pull request merged**
