### PR TITLE
Enable running tests for Travis CI builds

### PR DESCRIPTION
**Pull request by Andy-Wilkinson**

### CODE REVIEW

**Comment by Andy-Wilkinson** [comment]
WIP - Just enabling testing in Travis as a baseline for the fix...

**Comment by Andy-Wilkinson** [comment]
Okay.... That seems to have done the job,

> === TEST EXECUTION SUMMARY ===
   ImageSharp.Tests  Total: 1337, Errors: 0, Failed: 0, Skipped: 0, Time: 74.964s

**Comment by Andy-Wilkinson** [comment]
A bit of background on the fix for future reference.

Issue: The current build of xUnit seems to corrupt the state of any `Vector4 `instances passed via `[MemberData(...)]` (in fact this is true of even a simple struct with four fields of type `float`). I will submit this as a bug to the xUnit team.

Workaround: Pass the vector components as a float[], then recreate the `Vector4 `in the test itself.

**Comment by tocsoft** [comment]
Thanks a lot for this. Getting the tests running on linux is great. 👍

**Comment by Andy-Wilkinson** [comment]
I've opened an issue on the xUnit repo too - https://github.com/xunit/xunit/issues/1069

**Comment by olivif** [comment]
Great fix, pretty interesting bug on xUnit. Thanks Andy!

**Pull request merged**
