### PR TITLE
Docs

### LINKED ISSUE #6: API docs
_From @JimBobSquarePants on January 13, 2016 0:43_

I would like to create documentation like the following: 

http://dotnet.github.io/

MS are using the library below but I can't seem to follow the instructions.

http://dotnet.github.io/docfx/

_Copied from original issue: JimBobSquarePants/ImageProcessor#297_

### PR DESCRIPTION
**Pull request by M-Zuber**
Fixes #6

### CODE REVIEW

**Comment by M-Zuber** [comment]
There is actually a missing step - the appveyor build then needs to push the resulting contents of docs/ to the repo - other wise there will be nothing to display.

That has to happen on your end though, as it will involve setting a key in AV settings ([see here for some related material](https://wyam.io/docs/deployment/appveyor))

**Comment by tocsoft** [comment]
This isn't going to currently work with the build setup we're using. The build process doesn't use nuget restore (we use `dotnet restore`) or msbuild (`dotnet build`) for project building so at the moment on the CI server this isn't being built at all. 

You will need to add the below 2 to our appveyor.yml
```
before_build:
  - ps: |
        if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE)
        {
            git checkout $env:APPVEYOR_REPO_BRANCH -q
            cinst docfx -y
        }
```

```
after_build:
  - ps: |
        if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE)
        {
            docfx ./src/docs/docfx.json
        }
```
That will bypass the msbuild requirements by just using the docfx cli.

@JimBobSquarePants the after build step (see example below) is where the tweaks to make it publish the docs to where ever the commit is needed to go (my vote would be to either a dedicate repo or the gh-pages branch on this one to avoid a lot of churn on the main commit history). 
 https://github.com/docascode/docfx-seed/blob/master/appveyor.yml

**Comment by JimBobSquarePants** [comment]
@tocsoft Thanks for the extra info. Realistically we should only be pushing the doc changes when commited on the main branch with our work going on in a develop branch (which I plan to create and make default soon). That should considerable reduce our churn.

**Comment by M-Zuber** [comment]
So I started playing around with switching this from `docfx` to `wyam`.
In order to get a feel of how it looks, maybe we should have a call?

**Comment by M-Zuber** [comment]
I have the basic docs building - where I am holding is how to edit the `appveyor.yml` to do what needs to be done.
https://github.com/Drawaes/CondenserDocs/blob/master/appveyor.yml is an example of how most repos use `wyam +AV`, any thoughts on that flow?

**Comment by M-Zuber** [comment]
Ping @JimBobSquarePants

**Comment by JimBobSquarePants** [comment]
Will have to check with @tocsoft on the appveyor stuff but I'll build the docs locally today and have a play around.

**Comment by JimBobSquarePants** [comment]
@M-Zuber Is this PR up to date? I can't see any Wyam stuff.

**Comment by M-Zuber** [comment]
😢 I forgot to push it, will push it now.

The basis of the script is;
- Get wyam
- Remove old docs
- Push new docs

It is possible that it could still work even with a `/docs` folder.

Re the conversation in gitter on having docs per version, it is doable but requires a bit more work

**Comment by JimBobSquarePants** [comment]
I'm gonna merge this in now so I can start working on the VS2017 version. Will figure out how to do a new Docs recipe later. Cheers for all your help! 💯

**Comment by daveaglick** [comment]
🎉

I've got some suggestions on how to improve file organization since this is sharing the same repo as the main codebase (for example, "input" isn't exactly a clear folder name outside the context of a docs-specific repo). I'll put together a PR - ping me late next week if I forget.

**Comment by JimBobSquarePants** [comment]
Thanks @daveaglick. Appreciated, btw great work Wyam is impressive!

If you hold off til then it'll be easier to manage the merge. I'm trying to convert the project to 2017 just now and it might be easier to do after that.

**Comment by daveaglick** [comment]
I'll take a sanctioned excuse to procrastinate any day

**Comment by JimBobSquarePants** [comment]
@daveaglick Dropping you a ping here as I will need your help. I want to use the docs recipe but use my own theme/markup with http://responsivebp.com/ It seems like I should replace each cshtml file with my own but a few pointers would be most appreciated.

**Pull request merged**
