### PR TITLE
Adding missing documentation and fixing style issues.

### PR DESCRIPTION
**Pull request by olivif**
I noticed the project had 124 stylecop warnings, so I fixed a few (down to 70 after this PR). Would be great to fix all and set warnings as errors on the project to get build time protection on this.

### CODE REVIEW

**Comment by dlemstra** [comment]
Thanks for helping us out with fixing those warnings. I noticed that some of your params/returns don't start with a capital letter. I know it is a bit OCD but could you change that?

**Comment by olivif** [comment]
thanks @dlemstra. fixed the uppercase issue now. I also looked into if this can be a stylecop rule, so we can automate it, unfortunately couldn't find anything 😞

**Comment by dlemstra** [comment]
There is a StyleCop rule for this but it has not yet been implemented. I am waiting on my pull request (https://github.com/DotNetAnalyzers/StyleCopAnalyzers/pull/2242) being accepted and then can we enable the rule in this project.

**Comment by olivif** [comment]
@dlemstra awesome!

**Comment by JimBobSquarePants** [comment]
Ah this is great! I'm trying to make the code as readable as possible so this really helps. 👍

**Comment by olivif** [comment]
Thanks for merging! Yes, I have some more ideas on how to improve it, just wanted to start with a small-ish PR to kick things off :smile:

**Comment by JimBobSquarePants** [comment]
That's great to hear! Thanks for helping out 😄

**Pull request merged**
