### PR TITLE
Adding missing documentation and fixing style issues - part 2

### PR DESCRIPTION
**Pull request by olivif**
Alright, down to 12 warnings 🎉!!! Added more summaries and docs. Ignored one rule where I think it actually makes more sense to keep the code as is. 

I need some input on the remaining 12 warnings and how to best fix them, I filed an issue so we can discuss the approach there - #48.

### CODE REVIEW

**Comment by dlemstra** [comment]
Can you rebase this pull request? I made some changes to Bootstrapper.cs that broke this.

**Comment by olivif** [comment]
thanks @dlemstra, just rebased and fixed all the remaining warnings. 0 warnings 🎈

**Comment by olivif** [comment]
OK I found the bug and fixed it, it was super interesting actually. 

Here's what I did, I changed the `Bytes Bytes` field in the `JpegDecoderCore` from an internal field to a private backing field with a get only property. However, because Bytes is a mutable struct, this line would no longer work as intended, since we were changing the Bytes struct on a copy really. 

`byte c = decoder.Bytes.ReadByteStuffedByte(decoder.InputStream, out errorCode);`

So the fix was to make sure we reflect the changes property on the internal bytes. 

```
// Grab the decode bytes, use them and then set them
// back on the decoder.
var decoderBytes = decoder.Bytes;
byte c = decoderBytes.ReadByteStuffedByte(decoder.InputStream, out errorCode);
decoder.Bytes = decoderBytes;
```

**Comment by dlemstra** [comment]
Thanks for the fix 🙌. I pushed a patch to make sure that OpenCover will return the exit code from the test. It should now fail when it does not pass the tests.

**Comment by olivif** [comment]
@dlemstra awesome!

**Comment by JimBobSquarePants** [comment]
Whoop! 🎉

**Comment by dlemstra** [comment]
Great success 👏 All the warnings are gone (after I fixed one that I just added 👎)

**Comment by olivif** [comment]
Thanks for merging guys. Indeed, it was so rewarding to see zero warnings :smile:

We can consider enabling warnings as errors so we can't accidentally introduce some more before it gets out of control. Maybe if we can only do it on appveyor builds? It's a bit excessive and annoying to not be able to build locally because of stylecop.

**Comment by dlemstra** [comment]
I just enabled warnings as errors for the release build. And AppVeyor does a release build so that should prevent us adding extra warnings.

**Comment by JimBobSquarePants** [comment]
And the winner of the "First person to push errors" award goes to me!

**Pull request merged**
