### PR TITLE
Issue #132: Handle undefined EXIF data type where no number of compon…

### PR DESCRIPTION
**Pull request by blackcity**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/JimBobSquarePants/ImageSharp/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practise as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description
#132. Some applications do not set `NumberOfComponents `in EXIF data even if the type is `Undefined`. 

EXIF data of type `Undefined `with number of components not set (numberOfComponents == 0) is handled differently between ExifReader and ExifWriter. ExifReader handles it as byte array (4 bytes) while ExifWriter handles it as single byte. This results in an InvalidTypeCast exception.
<pre>
       private int WriteValue(ExifDataType dataType, object value, byte[] destination, int offset)
        {
             switch (dataType)
            {
                case ExifDataType.Byte:
                case ExifDataType.Undefined:
                    destination[offset] = (byte)value;
                    return offset + 1;
                [...]
            }
        }
</pre>

This PR sets the number of components to 4 (Exif inline value length) if type is Undefined and numberOfComponents is 0.

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
Is this a fix for #132 ? Awesome and thank you! I'll look at it asap.

**Comment by blackcity** [comment]
Yes, fixes #132 and related issues with those weird EXIF values.

**Comment by JimBobSquarePants** [comment]
Great stuff! Thanks for taking the time to submit a fix.

**Comment by dlemstra** [comment]
This project is using the same code as my Magick.NET project and I tried to apply your fix there. But your unit test passes without any problems without the patch applied. You can see my test in the referenced commit.

**Comment by blackcity** [comment]
I thought the same the first time I saw this error. But, there is no error during **reading** the EXIF data. The exception occurs later when the image is saved. Then ExifWriter tries to cast the byte array to a single byte:
<pre>
private int WriteValue(ExifDataType dataType, object value, byte[] destination, int offset)
{
     switch (dataType)
    {
        case ExifDataType.Byte:
        case ExifDataType.Undefined:
            destination[offset] = (byte)value;   // value is a byte Array -> InvalidCastException
            return offset + 1;
        [...]
    }
}
</pre>

But source of the problem is in ExifReader, because the Exif type `Undefined` should not have `NumberOfComponents` set to 0. And this is what the test does, it checks that `NumberOfComponents != 0`:
<pre>
if (entry.DataType == ExifDataType.Undefined)
{
    Assert.NotEqual(0, entry.NumberOfComponents);
}
</pre>

Btw, `NumberOfComponents` can have any value greater than 0 with ExifType `Undefinded`. But if it's 0 it must be set to 4 as a fallback, we handle it now as number of bytes. So in my opinion your test is not correct because NumberOfComponents can have any value except 0. Your test:
<pre>
if (value.DataType == ExifDataType.Undefined) 
{ 
    Assert.AreEqual(4, value.NumberOfComponents);
}
</pre> 

If you want to have the exception, just save the image in the unpatched version and ExifWriter will throw an `InvalidCastException`.

**Comment by dlemstra** [comment]
Maybe I was not being clear enough. When I only add the unit test to my project it passes but I would expect it to fail. I ran the test through the debugger and there are two values that are ` ExifDataType.Undefined`. One has the value `1` for `NumberOfComponents` and the other one has `4` as the value. This means it will pass the unit test if you check if the value is not `0`. This is before applying your fix in `ExifReader.cs`.

**Comment by blackcity** [comment]
Ok, misread your note. Thanks.

**Comment by blackcity** [comment]
Unit test updated. Since `NumberOfComponents` has a default value of 1 the previous version always passed the test.

**Comment by JimBobSquarePants** [comment]
@dlemstra As soon as you're happy with this could you do the merge please. You're the boss of this part.

**Pull request merged**
