### PR TITLE
Jpeg Decoder: split decoder phases, refactor error handling, allow EOF in scans, fix #18

### LINKED ISSUE #18: Progressive jpeg with missing EOI marker throws EOFException
_From @gdoron on October 31, 2016 12:57_

Hi James @JimBobSquarePants,

This specific image: 
image
fails when trying to load it.

Stacktrace:

>ImageProcessorCore.Formats.JpegDecoderCore+EOFException: Exception of type 'ImageProcessorCore.Formats.JpegDecoderCore+EOFException' was thrown.
   at ImageProcessorCore.Formats.JpegDecoderCore.Fill()
   at ImageProcessorCore.Formats.JpegDecoderCore.ReadByte()
   at ImageProcessorCore.Formats.JpegDecoderCore.ReadByteStuffedByte()
   at ImageProcessorCore.Formats.JpegDecoderCore.EnsureNBits(Int32 n)
   at ImageProcessorCore.Formats.JpegDecoderCore.DecodeHuffman(Huffman huffman)
   at ImageProcessorCore.Formats.JpegDecoderCore.Refine(Block b, Huffman h, Int32 zigStart, Int32 zigEnd, Int32 delta)
   at ImageProcessorCore.Formats.JpegDecoderCore.ProcessStartOfScan(Int32 n)
   at ImageProcessorCore.Formats.JpegDecoderCore.Decode[TColor,TPacked](Image`2 image, Stream stream, Boolean configOnly)
   at ImageProcessorCore.Image`2.Decode(Stream stream)
   at ImageProcessorCore.Image`2.Load(Stream stream)
   at Yooocan.Logic.ImageLogic.Resize(Stream stream, Int32 quality, Nullable`1 width, Nullable`1 height)

Any clue?

By the way, checkout this story: https://yooocan.com/Story/329/Having-Wheels-Has-Its-Perks
Amazing people, and you're helping them James!

THANKS A LOT!

_Copied from original issue: JimBobSquarePants/ImageProcessor#505_

### PR DESCRIPTION
**Pull request by antonfirsov**
The main goal of this refactor was fixing #18, but - as usually - things escalated.

1. To allow EOF-s during scans (specially in progressive case), I needed to do all the block transforming after the stream decoding is done. This resulted in a strict separation of decoding steps.  It makes `JpegDecoderCore.Decode()`  as simple as:
```
this.ProcessStream(image, stream, metadataOnly);
if (!metadataOnly)
{
    this.ProcessBlockColorsIntoJpegImageChannels<TColor>();
    this.ConvertJpegPixelsToImagePixels(image);
}
```

2. To keep error management in a sane way, allowing (but not forcing!) exceptions, I introduced the following pattern for various input reader/processor methods:

```
public DecoderErrorCode ReadFullUnsafe(byte[] data, int offset, int length)
{
	......
}

public void ReadFull(byte[] data, int offset, int length)
{
    DecoderErrorCode errorCode = this.ReadFullUnsafe(data, offset, length);
    errorCode.EnsureNoError(); // Throws an exception if errorCode != DecoderErrorCode.NoError
}
```
This allows incremental refactor of error handling code from exception-based error handling to C-style spaghetti. We need to avoid exceptions  to have the same decoder performance for users with broken input images.

3. To compensate the negative performance impact of the new error-handling `if`-s I did an optimization on Huffman decoding code by converting data to `int` (almost) everywhere. This eliminates unnecessary conversions.

3. Did various refactors and code cleanups, like moving all the input reading buffering logic to a separate `InputProcessor` type.

4. The separation of scan huffman decoding (`JpegScanDecoder.DecodeBlocks()`) from the logic converting blocks into YCbCr images (`JpegScanDecoder.ProcessBlockColors()`) allowed parallel execution of `ProcessBlockColors` calls.

*An overall before vs after benchmark comparsion:*

**Before the refactor**

```
                                Method |   InputCategory |        Mean |    StdDev | Scaled | Scaled-StdDev | Allocated |
-------------------------------------- |---------------- |------------ |---------- |------- |-------------- |---------- |
     'DecodeJpegMultiple - ImageSharp' |       AllImages | 374.3229 ms | 1.2255 ms |   2.89 |          0.02 |  56.38 MB |
 'DecodeJpegMultiple - System.Drawing' |       AllImages | 129.4012 ms | 1.1507 ms |   1.00 |          0.00 |   5.78 MB |
     'DecodeJpegMultiple - ImageSharp' | LargeImagesOnly | 294.9569 ms | 0.4662 ms |   3.41 |          0.02 |  43.66 MB |
 'DecodeJpegMultiple - System.Drawing' | LargeImagesOnly |  86.5401 ms | 0.5083 ms |   1.00 |          0.00 |   5.29 MB |
     'DecodeJpegMultiple - ImageSharp' | SmallImagesOnly |  76.7843 ms | 0.4196 ms |   1.81 |          0.01 |  12.74 MB |
 'DecodeJpegMultiple - System.Drawing' | SmallImagesOnly |  42.3149 ms | 0.2948 ms |   1.00 |          0.00 | 489.48 kB |
```

**After the refactor**
```
                                Method |   InputCategory |        Mean |    StdDev | Scaled | Scaled-StdDev | Allocated |
-------------------------------------- |---------------- |------------ |---------- |------- |-------------- |---------- |
     'DecodeJpegMultiple - ImageSharp' |       AllImages | 312.7559 ms | 1.0043 ms |   2.38 |          0.01 |  56.42 MB |
 'DecodeJpegMultiple - System.Drawing' |       AllImages | 131.5888 ms | 0.4324 ms |   1.00 |          0.00 |   5.78 MB |
     'DecodeJpegMultiple - ImageSharp' | LargeImagesOnly | 252.4911 ms | 0.5561 ms |   2.83 |          0.02 |  43.67 MB |
 'DecodeJpegMultiple - System.Drawing' | LargeImagesOnly |  89.2732 ms | 0.8507 ms |   1.00 |          0.00 |   5.29 MB |
     'DecodeJpegMultiple - ImageSharp' | SmallImagesOnly |  68.0404 ms | 0.5855 ms |   1.57 |          0.02 |  12.74 MB |
 'DecodeJpegMultiple - System.Drawing' | SmallImagesOnly |  43.2593 ms | 0.4677 ms |   1.00 |          0.00 | 489.48 kB |
```

+1 `ImageSharp.Sandbox46` is now executable, and it's possible to execute BenchmarkDotNet benchmarks. This was needed to enable profiling options unavailable in test runners, like memory profiling

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
Shia LaBeouf Slow Clap

Gotta say this is some of the most impressive refactoring work i've ever seen, well done!

I've identified a small issue though. It looks like we are somehow missing the data from the first MCU. This happens in both baseline and progressive jpegs. I couldn't see an obvious cause but I'm sure you'll spot the issue straight away.

turtle

We'll need to update the path in DecodeJpeg benchmark also to match new structure.

**Comment by antonfirsov** [comment]
I always checked my outputs, so stupid I missed this anomaly in the left corner :smile:

**Comment by JimBobSquarePants** [comment]
Don't worry, I almost did too! :smile:

**Comment by antonfirsov** [comment]
I think I fixed it. Need to be careful with `Array.Length`on rented arrays...

@JimBobSquarePants @dlemstra @tocsoft anyone interested in a review? Or should we just Merge N'Go? :smile:

**Comment by JimBobSquarePants** [comment]
Great stuff! I got caught out a few times with that when deallocating the png encoder.  I'll review this sometime this evening. Gotta date by the pool this afternoon. :smile:

**Comment by antonfirsov** [comment]
Ohh that Southern Hemisphere alternative universe... :smile:

**Comment by JimBobSquarePants** [comment]
All tests are passing and all looks clean so I'm gonna merge this. Only thing I would change would be the name of `Array` struct in `DecodedBlockMemento` just to avoid clashes.

**Comment by antonfirsov** [comment]
Okkay! Thanks!

**Comment by antonfirsov** [comment]
FYI: the cause of codecov-io complainments is the lack of tests for the new error handler `else` branches in the Jpeg Decoder. We need more bad input images for exhaustive "EOF-tolerance" testing.

**Comment by JimBobSquarePants** [comment]
I thought it would be something like that. Thanks for confirming.

**Pull request merged**
