### PR TITLE
Add ImageSharp.Sandbox46 to the test projects

### PR DESCRIPTION
**Pull request by antonfirsov**
**UPDATE:**
Just updated my R# to the newest [2016.3.1 version](https://www.jetbrains.com/resharper/download/). For me it works perfectly with .NET Core test projects! It means the extra sandbox project is no longer useful for R# users! 

Can anyone confirm if it's possible to profile test cases from the vanilla VS2015 Test Explorer using `Sandbox46`?

---
Solves #66. 

See the [README.md](https://github.com/antonfirsov/ImageSharp/blob/add-sandbox46/tests/ImageSharp.Sandbox46/README.md) of the project!

### CODE REVIEW

**Comment by tocsoft** [comment]
I confirm managed to get the profiler to run against a test case 👍

**Comment by JimBobSquarePants** [comment]
DotTrace yeah? It's throwing for me when testing cases inherit `FileTestBase`

```
The type initializer for 'ImageSharp.Tests.FileTestBase' threw an exception.

Unable to find Formats directory at any of these locations [C:\Program Files\dotnet\TestImages\Formats\, C:\Program Files\dotnet\tests\ImageSharp.Tests\TestImages\Formats\, C:\TestImages\Formats\]
   at ImageSharp.Tests.GeneralFormatTests.DecodeThenEncodeImageFromStreamShouldSucceed() in C:\development\github\ImageSharp\tests\ImageSharp.Tests\Formats\GeneralFormatTests.cs:line 53
   at ImageSharp.Tests.TestFile.Create(String file) in C:\development\github\ImageSharp\tests\ImageSharp.Tests\TestFile.cs:line 89
   at ImageSharp.Tests.FileTestBase..cctor() in C:\development\github\ImageSharp\tests\ImageSharp.Tests\FileTestBase.cs:line 19
   at ImageSharp.Tests.TestFile.GetFormatsDirectory() in C:\development\github\ImageSharp\tests\ImageSharp.Tests\TestFile.cs:line 151
   at ImageSharp.Tests.TestFile..cctor() in C:\development\github\ImageSharp\tests\ImageSharp.Tests\TestFile.cs:line 27

```

**Comment by antonfirsov** [comment]
@JimBobSquarePants added a quickfix to this PR to address your issue.

Now R# users should be capable to profile tests without the use of  the `Sandbox46` project, however based on @tocsoft -s feedback it is still useful for vanilla VS users.

Should we merge this? Any concerns?

**Comment by JimBobSquarePants** [comment]
No concerns, merge away 👍

**Pull request merged**
