### PR TITLE
[WIP] Add support for DrawString extension method

### LINKED ISSUE #38: Font Support
The library will at some point need to add font support.

Libraries to consider basing the system on.

- https://github.com/MikePopoloski/SharpFont
- https://github.com/LayoutFarm/Typography

Ideally we shouldn't have any dependencies and absolutely no unmanaged dependencies as we need to deploy easily on web applications.

### PR DESCRIPTION
**Pull request by tocsoft**
Created a new project to spin drawing.text out, currently this embeds a copy of  font loading code from https://github.com/LayoutFarm/Typography could be switched out later to be a nuget dependency.

Currently only support limited text layout, only supports left justified text with manual newlines (no wrapping support).

This supports drawing the text with any brush, out outlined with any pen (patterned pens just don't really work properly because of all the curves).

Support TTF fonts, and the code only support the standard/single variant in the file therefore if you want bold/italic text then you need to have yourself a bold/italic version of the *.ttf file.

Fixes #38

### CODE REVIEW

**Comment by tocsoft** [comment]
Some performance numbers.

``` ini

BenchmarkDotNet=v0.10.1, OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i5-4690 CPU 3.50GHz, ProcessorCount=4
Frequency=3417967 Hz, Resolution=292.5716 ns, Timer=TSC
  [Host]     : Clr 4.0.30319.42000, 64bit RyuJIT-v4.6.1586.0 [AttachedDebugger]
  DefaultJob : Clr 4.0.30319.42000, 64bit RyuJIT-v4.6.1586.0


```
                       Method |      Mean |    StdDev | Scaled | Scaled-StdDev |     Gen 0 |    Gen 1 |    Gen 2 | Allocated |
----------------------------- |---------- |---------- |------- |-------------- |---------- |--------- |--------- |---------- |
 'System.Drawing Draw String' | 2.4708 ms | 0.0397 ms |   1.00 |          0.00 | 1216.6667 | 396.3542 | 396.3542 |   5.15 MB |
     'ImageSharp Draw String' | 6.4101 ms | 0.0734 ms |   2.60 |          0.05 |  772.9167 | 716.6667 | 710.4167 |   7.69 MB |

**Comment by tocsoft** [comment]
### And of course shinyness
#### Loading up a font and configuring it
```c#
using (FileStream stream = File.OpenRead("pathtofile.ttf"))
{
    this.font = new Font(stream)
    {
        // no font weight, style as we don't yet support loading multiple variants from a single file.
        EnableKerning = true, // default value
        LineHeight = 1.5f,  // default value
        Size = 40, // default value is 10
        TabWidth = 4 // default value
    };
}
```
_All the below example assume font has already been loaded, and image has been created with a solid blue background._

#### Simple text with all defaults
```c#
using (FileStream output = File.OpenWrite("out.png"))
{
    image
        .DrawString("Hello World", font, Color.HotPink, new Vector2(10, 10))
        .Save(output);
}
```
simple

#### Text with newline 

```c#
using (FileStream output = File.OpenWrite("out.png"))
{
    image
        .DrawString("Hello\nWorld", font, Color.HotPink, new Vector2(10, 10))
        .Save(output);
}
```
newline

#### With Antialiasing disabled
```c#
using (FileStream output = File.OpenWrite("out.png"))
{
    image
        .DrawString("Hello World", font, Color.HotPink, new GraphicsOptions(false), new Vector2(10, 10))
        .Save(output);
}
```
noantialiasing

#### With a 1px solid outline
```c#
using (FileStream output = File.OpenWrite("out.png"))
{
    image
        .DrawString("Hello World", font, Pens.Solid(Color.HotPink, 1), new Vector2(10, 10))
        .Save(output);
}
```
outline

#### With some tabs
```c#
using (FileStream output = File.OpenWrite("out.png"))
{
    image
        .DrawString("Helli\tWorld\nHello\tWorld", font, Color.HotPink, new Vector2(10, 10))
        .Save(output);
}
```
withtab

**Comment by tocsoft** [comment]
Been thinking a bit more about this PR, while we're still deciding exactly how to handle splitting the library up into multiple project is it worth me moving this back into the core `ImageSharp` project and drop the `ImageSharp.Drawing.Text` project for now, especially as i'm not actually adding any external dependencies with this?

@JimBobSquarePants what do you think? move it directly into the main project for now and worry about splitting it down once someone has gotten there head around handling the multi projects? or leave it as is?

**Comment by prepare** [comment]
@tocsoft 
> 'ImageSharp Draw String'  perf:  6.4101 ms  stddev:	0.0734 ms

slower more than System.Drawing about 3 times!

Do you what are the slow points?,
Is it from the Typography?
Do you load font each time before rendering?
or load once and use glyph cache?

**Comment by prepare** [comment]
glyph cache:
    load font once -> store each generated glyphs in glyph cache.
    then scale it later for each request glyph size

**Comment by JimBobSquarePants** [comment]
@tocsoft Let's see if we can get this build situation sorted. It might well take our combined powers but we really should be separating the projects as early as possible. 

I'll leave you and @prepare to chat performance for now as I'll really need to study the code in order to spot anything and you will both already know where to look when optimizing. 

On embedding the library. @prepare What are your plans for LayoutFarm/Typography? Will there be a nuget package we could rely on and if so, what will be the base install availability. I hear NetStandard 1.1 is possible?

**Comment by prepare** [comment]
currently I have no plan about  LayoutFarm/Typography's nuget packet.
I use a shared source technique for integration with other projects.

I will ask @vidstige for a nuget package.

---
Hello @vidstige,
You may have your nuget packet customer here :) 
please consider this.

NOpenType-based code is used in this Repo.
It may be better with nuget packet of NOpenType.

**Comment by vidstige** [comment]
Hi @JimBobSquarePants , I'm original author of NOpenType. I've only skimmed through this issue, but I'm under impression you would like to consume a NuGet package in ImageSharp rather than copying in source code, is this correct? I've been wanting to do an NyGet package already for @prepare but never got around doing it. But I'll try to publish a first NuGet package and ping you. Please not that the source code you have been using might have converged from the original.

**Comment by tocsoft** [comment]
@vidstige It would be awesome having a nuget package, I wasn't really happy pulling in the source code directly, Its fine if its diverged a bit I'm sure i'll be able to integrate your changes, looking at your repo it looks like we'll be able to move over to your repo/package using an `IGlyphRasterizer` and it should work fine, only thing I notice is your version doesn't seem to support kerning and that's currently enabled in our usage.

**Comment by vidstige** [comment]
@tocsoft cool! Hopefully I've got time tonight (I'm in CET) to publish a NuGet. For the kerning, perhaps we can help out and get those changes into the NRasterizer repo?

**Comment by tocsoft** [comment]
awesom.. I've added  vidstige/NRasterizer#33  continue any required kerning discussion on your repo.

**Comment by JimBobSquarePants** [comment]
Hi @vidstige good to hear from you and excellent work on your package!

Yeah, we'd really like to support your library rather than simply taking source code so we thought consuming a nuget package would be a good way to do it. That way any changes or improvements we make can be made directly in your repo and benefit everybody. 

One thing we need to be sure of though is minimum framework support. At the moment with your code integrated directly we are able to support netstandard 1.1. Is that something you will be able to easily support?

**Comment by tocsoft** [comment]
Will hold this until vidstige/NRasterizer#32 lands and move over to the nuget version of the lib.

**Comment by vidstige** [comment]
Yeah, the library uses very little of the .NET platform from what I can recall. I'll try to run it with 1.1 (this is .NET 4.5 right?) and see how that works out. I think it even runs on .NET 2.0.

**Comment by vidstige** [comment]
Alright, NuGet package is up. Let me know if it works out for you guys. It does not have kerning yet though.

**Comment by prepare** [comment]
from readme (on first page)

> **What might never happen**
> 
>  Font support. I don't know where to start coding this so if you have any pointers please chip in.
> 

@JimBobSquarePants:

 you may need to fix that part a little bit  :)

**Comment by dlemstra** [comment]
@ vidstige Your NuGet package seems to target net20 instead of netstandard. Are you planning to support netstandard?

**Comment by tocsoft** [comment]
@dlemstra see vidstige/NRasterizer#36 I've already sent across a PR to enable netstandard1.1 support... just having some build server fun first.

**Comment by tocsoft** [comment]
superseded by #124

**Pull request closed without merging**
