### PR TITLE
Reducing allocations in color spaces. 

### PR DESCRIPTION
**Pull request by olivif**
Making some constants static to reduce the number of allocations.

### CODE REVIEW

**Comment by antonfirsov** [comment]
@olivif these constants seem to be quite common, I'm using them same ones in Jpeg across multiple classes. Don't we need a common place for them in `ImageSharp/Numerics` or `ImageSharp/Colors`? @dlemstra @JimBobSquarePants @tocsoft Your thoughts?

**Comment by tocsoft** [comment]
Most of these constants seem to be to be very specific to the particular color space they are declared in, I would probably leave these where they are. 

I think the only ones that make me stop and question is the `VectorX.Zero` ones but at the same time I can see it makes the code more readable and consistent across color spaces so I would be inclined to let them pass.

**Comment by olivif** [comment]
Yes, I considered moving them out but I had the same thought as @tocsoft, they are very specific to the class.

**Comment by antonfirsov** [comment]
Ok, actually only `new Vector4(255)` seems to be super-common, maybe it doesn't worth to create a utility class only for this.

PS:
@olivif this change does not reduce number of allocations, because `Vector4` is a value type. The code looks definitely better, but I'm not sure about the effects on performance, they can be even negative! It could be tested by inlining the constants in [DCT.cs](https://github.com/JimBobSquarePants/ImageSharp/blob/master/src/ImageSharp/Formats/Jpg/Components/DCT.cs).

**Comment by JimBobSquarePants** [comment]
What's the current opinion on this? I'll need to be merged before #64

**Comment by antonfirsov** [comment]
I just wanted to clear some misunderstandings. The code is definitely better, I think we should merge it now!

**Comment by olivif** [comment]
thanks for merging guys! you are right on the allocations @antonfirsov, forgot Vector3/4 are structs 😄

**Pull request merged**
